# Generated by Django 5.0.7 on 2025-08-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(max_length=100)),
                ('Total_person', models.CharField(max_length=2)),
                ('Adate', models.CharField(max_length=10)),
                ('Ldate', models.CharField(max_length=10)),
                ('Personaldata', models.TextField()),
            ],
        ),
    ]
