# Generated by Django 5.0.7 on 2025-08-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMeYatraApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('pickup_point', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('alt_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('persons', models.PositiveIntegerField()),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
