# Generated by Django 5.0.7 on 2025-08-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMeYatraApp', '0002_tripbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripbooking',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
