# Generated by Django 5.2.5 on 2025-08-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMeYatraApp', '0003_tripbooking_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('to_location', models.CharField(max_length=100)),
                ('total_seats', models.PositiveIntegerField()),
            ],
        ),
    ]
