# Generated by Django 5.2.5 on 2025-08-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GetMeYatraApp', '0004_tripdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripDate',
        ),
    ]
