# Generated by Django 5.2.5 on 2025-08-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetMeYatraApp', '0005_delete_tripdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='tour_images/')),
                ('description', models.TextField()),
                ('full_description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('meals', models.CharField(max_length=100)),
                ('transportation', models.CharField(max_length=100)),
                ('pickup_points', models.CharField(max_length=200)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itinerary', models.TextField()),
                ('inclusions', models.TextField()),
                ('exclusions', models.TextField()),
                ('important_note', models.TextField()),
                ('hotel_details', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
